### ISSUE TITLE
Icons don't work

### ISSUE THREAD

**Issue by pheianox** [speedenator/agnoster-bash#20]
My icons disappear, I don't know why 
![Screenshot_2020-10-25_03-33-56](https://user-images.githubusercontent.com/72671586/97101361-1ee05300-1673-11eb-9b98-0d22e3e00a3d.png)

**Comment by JahanzebNawaz** [comment]
the same thing happening to me, don't know why. did you found the solution. 
I'm using Ubuntu 20.04 LTS.

**Comment by ghost** [comment]
I believe this requires that you use a patched Powerline font.

**Comment by speedenator** [comment]
Correct - you have to use a Powerline font with the icons.
