### ISSUE TITLE
just install it but not look like the the screen shot

### ISSUE THREAD

**Issue by MacFlurry** [speedenator/agnoster-bash#3]
Hello, 
I just follow the installation steps and I got this

![capture d ecran 2017-04-23 a 18 05 45](https://cloud.githubusercontent.com/assets/8139322/25315094/ea1c442c-284f-11e7-8016-fb6d9f2f6f7b.png)

Can you help me to make it look like the original ? ( without question mark )

I tuning it with iTerm2 + Powerline + patch installed.

thanks for your help.

**Comment by speedenator** [comment]
It looks like on iterm you aren't using the power line font (profiles / text I think). You have to select them in addition to installing. I personally like dejavu or menlo.

Cheers,
-e

**Comment by MacFlurry** [comment]
Hello,

I selected Menlo, quit iterm and relaunch it.

![capture d ecran 2017-04-23 a 18 28 44](https://cloud.githubusercontent.com/assets/8139322/25315270/f7d25d1a-2852-11e7-913c-f393a80001a5.png)

still seeing the issue.

**Comment by MacFlurry** [comment]
thanks for helping me out

**Comment by MacFlurry** [comment]
have a look at this ....

![capture d ecran 2017-04-23 a 18 35 03](https://cloud.githubusercontent.com/assets/8139322/25315360/0e3c03e8-2854-11e7-8ec5-5674df4152e4.png)

**Comment by MacFlurry** [comment]
I solve the issue, 

Menlo is not part of PowerLine fonts, so I choose "Meslo"

Thanks a lot for your great work, I really appreciate :-)
